export const levelBarTheme = {
  // padding: 0,
  // marginLeft: 4,
  // bgcolor: "transparent",
  // backdropFilter: "invert(15%)",
  // borderRadius: 10,
  // minWidth: 350,
  // margin: 1,
  // height: 10,
  // boxShadow: " 0 0 2px 4px #ffffff",
  background: "rgba( 0, 0, 0, 0.4 )",
  boxShadow: "0 8px 32px 0 rgba( 163, 7, 7, 0.37 )",
  backdropFilter: "blur(5px)",
  minWidth: 350,
  borderRadius: "40px",
};
